import { IsString, IsOptional, IsBoolean, IsEnum, IsInt, IsNumber, Min, IsEmail, Matches, ValidateIf } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class CreateSubscriberDto {
  @ApiProperty() @IsString() username: string;
  @ApiProperty() @IsString() password: string;
  @ApiPropertyOptional() @IsOptional() @IsEnum(['regular', 'mac', 'docsis', 'dhcp_ipoe', 'mikrotik_acl', 'staros_acl', 'card', 'ias']) accountType?: string;
  @ApiPropertyOptional() @IsOptional() @IsEnum(['active', 'disabled', 'expired']) status?: string;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() enabled?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() verified?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() alertSent?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsString() macCpe?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() macCm?: string;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() macLock?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsEnum(['pool', 'dhcp', 'static']) ipModeCpe?: string;
  @ApiPropertyOptional() @IsOptional() @IsEnum(['pool', 'dhcp', 'static']) ipModeCm?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() staticIpCpe?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() staticIpCm?: string;
  @ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) simUse?: number;
  @ApiPropertyOptional() @IsOptional() @Matches(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, { message: 'planId must be a valid UUID format' }) planId?: string;
  @ApiPropertyOptional() @IsOptional() @Matches(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, { message: 'managerId must be a valid UUID format' }) managerId?: string;
  @ApiPropertyOptional() @IsOptional() @Matches(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, { message: 'groupId must be a valid UUID format' }) groupId?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() dlLimitBytes?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() ulLimitBytes?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() totalLimitBytes?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() expiryDate?: string;
  @ApiPropertyOptional() @IsOptional() @IsInt() timeLimitSecs?: number;
  @ApiPropertyOptional() @IsOptional() @IsNumber() balance?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() firstName?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() lastName?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() company?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() address?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() city?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() zip?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() country?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() state?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() phone?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() mobile?: string;
  @ApiPropertyOptional() @IsOptional() @ValidateIf(o => o.email !== '') @IsEmail() email?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() vatId?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() contractId?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() contractExpiry?: string;
  @ApiPropertyOptional() @IsOptional() @IsNumber() latitude?: number;
  @ApiPropertyOptional() @IsOptional() @IsNumber() longitude?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() language?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() comment?: string;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() emailAlerts?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() smsAlerts?: boolean;
  @ApiPropertyOptional() @IsOptional() customAttrs?: any[];
}
